server:
  port: 9090

spring:
  application:
    name: gateway-service
  main:
    allow-bean-definition-overriding: true

  cloud:
    nacos:
      discovery: #注册中心
        server-addr: 127.0.0.1:8837,127.0.0.1:8848,127.0.0.1:8859
      config: #配置中心
        server-addr: 127.0.0.1:8837,127.0.0.1:8848,127.0.0.1:8859
        file-extension: yaml
    gateway:
      discovery:
        locator:
          enabled: true #gateway可以从nacos发现服务，调用其他服务

      routes:
        #路由配置
        - id: user_service_route
          uri: lb://user-service #对应user-service的spring.application.name
          predicates:
            - Path=/** #断言配置，**无限制
          filters:
            - StripPrefix=1 #过滤器
        - id: oauth2_service_route
          uri: lb://oauth2-service
          predicates:
            - Path=/** #断言配置，**无限制
          filters:
            - StripPrefix=1 #过滤器

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/oauth?serverTimeZone=UTC&useSSL=false
#    username: root
#    password: root